apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ukopms4q5-nodejs
  janus-idp.io/tekton: ukopms4q5-nodejs
  backstage.io/kubernetes-id: ukopms4q5-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ukopms4q5-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
